-- 1. Insertar datos básicos de referencia
INSERT INTO TIPOUBICA (CODTIPOUBICA, DESCTIPOUBICA) VALUES ('PAS', 'País');
INSERT INTO TIPOUBICA (CODTIPOUBICA, DESCTIPOUBICA) VALUES ('DEP', 'Departamento');
INSERT INTO TIPOUBICA (CODTIPOUBICA, DESCTIPOUBICA) VALUES ('CIU', 'Ciudad');

INSERT INTO UBICACION (CODUBICA, UBI_CODUBICA, CODTIPOUBICA, NOMUBICA) 
VALUES ('COL', NULL, 'PAS', 'Colombia');

INSERT INTO UBICACION (CODUBICA, UBI_CODUBICA, CODTIPOUBICA, NOMUBICA) 
VALUES ('ANT', 'COL', 'DEP', 'Antioquia');

INSERT INTO UBICACION (CODUBICA, UBI_CODUBICA, CODTIPOUBICA, NOMUBICA) 
VALUES ('MED', 'ANT', 'CIU', 'Medellín');

INSERT INTO TIPOARCHIVO (IDTIPOARCHIVO, DESCTIPOARCHIVO) VALUES ('IM', 'Imagen');
INSERT INTO TIPOARCHIVO (IDTIPOARCHIVO, DESCTIPOARCHIVO) VALUES ('VD', 'Video');
INSERT INTO TIPOARCHIVO (IDTIPOARCHIVO, DESCTIPOARCHIVO) VALUES ('AU', 'Audio');
INSERT INTO TIPOARCHIVO (IDTIPOARCHIVO, DESCTIPOARCHIVO) VALUES ('DO', 'Documento');

INSERT INTO TIPOCONTENIDO (IDTIPOCONTENIDO, DESCTIPOCONTENIDO) VALUES ('MS', 'Mensaje simple');
INSERT INTO TIPOCONTENIDO (IDTIPOCONTENIDO, DESCTIPOCONTENIDO) VALUES ('MM', 'Multimedia');

INSERT INTO PROPIEDAD (IDPROPIEDAD, PRO_IDPROPIEDAD, DESCPROPIEDAD, VALORDEFECTO, VALORPROPIEDAD) 
VALUES ('PV', NULL, 'Privacidad perfil', 1, 'Público/Privado');

INSERT INTO PROPIEDAD (IDPROPIEDAD, PRO_IDPROPIEDAD, DESCPROPIEDAD, VALORDEFECTO, VALORPROPIEDAD) 
VALUES ('NT', 'PV', 'Notificaciones', 1, 'Activado/Desactivado');

-- 2. Insertar usuarios de prueba
INSERT INTO USUARIO (CONSECUSER, CODUBICA, USE_CONSECUSER, NOMBRE, APELLIDO, NOMBRE_USUARIO, FECHAREGISTRO, EMAIL, CELULAR) 
VALUES ('U0001', 'MED', NULL, 'Juan', 'Pérez', 'juanp', TO_DATE('01/01/2023', 'DD/MM/YYYY'), 'juan@example.com', '3001234567');

INSERT INTO USUARIO (CONSECUSER, CODUBICA, USE_CONSECUSER, NOMBRE, APELLIDO, NOMBRE_USUARIO, FECHAREGISTRO, EMAIL, CELULAR) 
VALUES ('U0002', 'MED', 'U0001', 'María', 'Gómez', 'mariag', TO_DATE('15/01/2023', 'DD/MM/YYYY'), 'maria@example.com', '3002345678');

INSERT INTO USUARIO (CONSECUSER, CODUBICA, USE_CONSECUSER, NOMBRE, APELLIDO, NOMBRE_USUARIO, FECHAREGISTRO, EMAIL, CELULAR) 
VALUES ('U0003', 'MED', 'U0001', 'Carlos', 'López', 'carlosl', TO_DATE('20/02/2023', 'DD/MM/YYYY'), 'carlos@example.com', '3003456789');

-- 3. Configuración de usuarios
INSERT INTO CONFIUSER (CONSECUSER, NCONFIGUSER, IDPROPIEDAD, ESTADO, VALOR) 
VALUES ('U0001', 1, 'PV', 1, 1);

INSERT INTO CONFIUSER (CONSECUSER, NCONFIGUSER, IDPROPIEDAD, ESTADO, VALOR) 
VALUES ('U0002', 1, 'PV', 1, 0);

-- 4. Crear grupos y asignar miembros
INSERT INTO GRUPO (CODGRUPO, GRU_CODGRUPO, CONSECUSER, NOMGRUPO, FECHAREGGRUPO, IMAGGRUPO) 
VALUES (1, NULL, 'U0001', 'Amigos del Colegio', TO_DATE('10/03/2023', 'DD/MM/YYYY'), EMPTY_BLOB());

INSERT INTO GRUPO (CODGRUPO, GRU_CODGRUPO, CONSECUSER, NOMGRUPO, FECHAREGGRUPO, IMAGGRUPO) 
VALUES (2, NULL, 'U0002', 'Familia', TO_DATE('15/03/2023', 'DD/MM/YYYY'), EMPTY_BLOB());

-- Configuración de grupo
INSERT INTO CONFIGRUPO (CODGRUPO, NCONFIGGRUPO, IDPROPIEDAD, ESTADO) 
VALUES (1, 1, 'PV', 1);

-- Asignar usuarios a grupos
INSERT INTO PERTENECE (CODGRUPO, CONSECUSER) VALUES (1, 'U0001');
INSERT INTO PERTENECE (CODGRUPO, CONSECUSER) VALUES (1, 'U0002');
INSERT INTO PERTENECE (CODGRUPO, CONSECUSER) VALUES (2, 'U0002');
INSERT INTO PERTENECE (CODGRUPO, CONSECUSER) VALUES (2, 'U0003');

-- 5. Establecer relaciones de amistad
INSERT INTO AMIGO (USE_CONSECUSER, CONSECUSER) VALUES ('U0001', 'U0002');
INSERT INTO AMIGO (USE_CONSECUSER, CONSECUSER) VALUES ('U0001', 'U0003');
INSERT INTO AMIGO (USE_CONSECUSER, CONSECUSER) VALUES ('U0002', 'U0003');

-- Relaciones de seguimiento
INSERT INTO SEGUIR (USE_CONSECUSER, CONSECUSER) VALUES ('U0001', 'U0002');
INSERT INTO SEGUIR (USE_CONSECUSER, CONSECUSER) VALUES ('U0002', 'U0001');

-- 6. Insertar mensajes y contenido (opcional)
INSERT INTO MENSAJE (USE_CONSECUSER, CONSECUSER, CONSMENSAJE, MEN_USE_CONSECUSER, MEN_CONSECUSER, MEN_CONSMENSAJE, CODGRUPO, FECHAREGMEN) 
VALUES ('U0001', 'U0002', 1, NULL, NULL, NULL, NULL, TO_DATE('20/03/2023 10:00', 'DD/MM/YYYY HH24:MI'));

INSERT INTO MENSAJE (USE_CONSECUSER, CONSECUSER, CONSMENSAJE, MEN_USE_CONSECUSER, MEN_CONSECUSER, MEN_CONSMENSAJE, CODGRUPO, FECHAREGMEN) 
VALUES ('U0002', 'U0001', 1, 'U0001', 'U0002', 1, NULL, TO_DATE('20/03/2023 10:05', 'DD/MM/YYYY HH24:MI'));

-- Insertar contenido asociado a mensajes
INSERT INTO CONTENIDO (USE_CONSECUSER, CONSECUSER, CONSMENSAJE, CONSECCONTENIDO, IDTIPOCONTENIDO, IDTIPOARCHIVO, CONTENIDOIMAG, LOCALIZACONTENIDO) 
VALUES ('U0001', 'U0002', 1, 1, 'MS', NULL, EMPTY_BLOB(), 'Hola María, ¿cómo estás?');